[package]
name = "TyrsTunes"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
eframe = "0.28.1"
rodio = "0.19.0"
rusqlite = { version = "0.29.0", features = ["bundled"] }
id3 = "1.14.0"
walkdir = "2.3.3"
rfd = "0.11.0"